
swagger: '2.0'
info:
  version: 1.0.0
  title: Domain API
  host: api.liveperson.net
  basePath: /http://api.liveperson.net/api/account/

paths:
  /{accountId}/service/{serviceName}/baseURI.json:
    get:
      parameters:
        - name: accountId
          in: query
          description: Account name
          required: true
          type: string
        - name: serviceName
          in: query
          description: Account name
          required: true
          type: string
      responses:
        200:
          description: OK
